# Generated by Django 3.2.7 on 2021-10-03 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heat_map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maps',
            new_name='Map',
        ),
    ]
