# Generated by Django 3.2.7 on 2021-10-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_map', '0002_rename_maps_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='name',
        ),
        migrations.RemoveField(
            model_name='map',
            name='text',
        ),
        migrations.AddField(
            model_name='map',
            name='lat_1',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='map',
            name='long_1',
            field=models.FloatField(default=1.0),
        ),
    ]
