# Generated by Django 3.2.7 on 2021-10-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_map', '0003_auto_20211013_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='map_choice',
            field=models.CharField(choices=[('1', 'Covid_Cases'), ('2', 'Median_Income'), ('3', 'Insurance_Coverage')], default='1', max_length=1),
        ),
    ]
