# Generated by Django 3.2.7 on 2021-11-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heat_map', '0004_map_map_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
    ]
