# Generated by Django 3.2.7 on 2021-11-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_covid_cases_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covid_cases',
            name='covid_cases_ID',
        ),
        migrations.AlterField(
            model_name='age',
            name='age_id',
            field=models.IntegerField(default=0, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='covid_cases',
            name='id',
            field=models.BigIntegerField(default=0, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='ethnicity_id',
            name='ethnicity_id',
            field=models.IntegerField(default=0, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='income_id',
            name='c_income_id',
            field=models.FloatField(default=0.0, primary_key='true', serialize=False),
        ),
    ]
