# Generated by Django 3.2.7 on 2021-11-03 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20211102_2222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='age',
        ),
        migrations.DeleteModel(
            name='ethnicity_id',
        ),
        migrations.DeleteModel(
            name='income_id',
        ),
    ]
