# Generated by Django 3.2.7 on 2021-11-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_alter_covid_cases_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid_cases',
            name='id',
            field=models.BigIntegerField(default=0, primary_key='true', serialize=False),
        ),
    ]
