# Generated by Django 3.2.7 on 2021-11-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_covid_deaths'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Age',
        ),
        migrations.DeleteModel(
            name='ethnicity_id',
        ),
        migrations.DeleteModel(
            name='income_id',
        ),
    ]
