# Generated by Django 3.2.8 on 2021-11-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_covid_deaths'),
    ]

    operations = [
        migrations.CreateModel(
            name='health_stats',
            fields=[
                ('id', models.BigIntegerField(default=0, primary_key='True', serialize=False)),
                ('county', models.CharField(default=0, max_length=100)),
                ('percent_insured', models.IntegerField(default=0)),
            ],
        ),
    ]
