# Generated by Django 3.2.7 on 2021-12-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_health_stats'),
        ('tables', '0011_alter_health_stats_percent_insured'),
    ]

    operations = [
    ]
