# Generated by Django 3.2.7 on 2021-12-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_profile_last_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_active',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_img',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_img_data',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigIntegerField(default=0, primary_key='true', serialize=False),
        ),
    ]
