# Generated by Django 3.2.9 on 2021-12-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_img',
            field=models.FileField(default='cat.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='cat.jpeg', upload_to='profile/photos'),
        ),
    ]
