# Generated by Django 3.2.9 on 2021-12-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_img_data',
        ),
    ]
