# Generated by Django 3.2.7 on 2021-11-29 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_alter_profile_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 14, 3, 29, 189468)),
        ),
    ]
