# Generated by Django 3.2.7 on 2021-12-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betablog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodels',
            options={'ordering': ('-date_created',)},
        ),
    ]
